name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish CMake-SBOM-Builder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Upload sbom.cmake to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: cmake/sbom.cmake
          file_glob: true
          overwrite: true